apiVersion: apps/v1
kind: Deployment
metadata:
  name: mana-archive
  namespace: mana-archive
spec:
  replicas: 1
  strategy:
    type: recreate
  selector:
    matchLabels:
      app: mana-archive
  template:
    metadata:
      labels:
        app: mana-archive
    spec:
      containers:
        - name: mana-archive
          image: ghcr.io/jasonvandeventer/mana-archive:v2.0.18
          imagePullPolicy: IfNotPresent
          env:
            - name: DATA_DIR
              value: /data
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: mana-archive-data
              mountPath: /data
      volumes:
        - name: mana-archive-data
          persistentVolumeClaim:
            claimName: mana-archive-data-longhorn
