apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mana-archive-data
  namespace: mana-archive
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
