apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - jobs/migrate-v3-4.yaml

images:
  - name: ghcr.io/jasonvandeventer/mana-archive
    newTag: v2.0.18
