apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mana-archive-new
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jasonvandeventer/mana-archive-platform.git
    targetRevision: HEAD
    path: k8s/apps/mana-archive
  destination:
    server: https://kubernetes.default.svc
    namespace: mana-archive
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
