apiVersion: v1
kind: Pod
metadata:
  name: lh-writer
  namespace: default
spec:
  restartPolicy: Never
  containers:
    - name: writer
      image: busybox:1.36
      command: ["/bin/sh", "-c"]
      args:
        - >
          echo "hello from longhorn" > /data/testfile.txt;
          date >> /data/testfile.txt;
          sync;
          echo "=== WRITTEN ===";
          cat /data/testfile.txt;
          sleep 3600
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: lh-test-pvc
